SKILL_KEYWORDS = [
    # Programming Languages
    "python",
    "java",
    "javascript",
    "typescript",
    "c",
    "c++",
    "c#",
    "php",
    "go",
    "ruby",
    "kotlin",
    "swift",
    # Frontend
    "html",
    "css",
    "bootstrap",
    "tailwind css",
    "react",
    "next.js",
    "angular",
    "vue",
    "jquery",
    # Backend
    "django",
    "django rest framework",
    "drf",
    "flask",
    "fastapi",
    "node.js",
    "express",
    "spring boot",
    "laravel",
    "asp.net",
    # Mobile
    "android",
    "ios",
    "react native",
    "flutter",
    # Databases
    "mysql",
    "postgresql",
    "mongodb",
    "sqlite",
    "redis",
    "oracle",
    "mariadb",
    "firebase",
    # Cloud
    "aws",
    "azure",
    "gcp",
    "digitalocean",
    # DevOps
    "docker",
    "docker compose",
    "kubernetes",
    "nginx",
    "jenkins",
    "github actions",
    "gitlab ci",
    "ci/cd",
    # Version Control
    "git",
    "github",
    "bitbucket",
    # APIs
    "rest api",
    "restful api",
    "graphql",
    "soap",
    # Python Libraries
    "pandas",
    "numpy",
    "matplotlib",
    "scikit-learn",
    "tensorflow",
    "keras",
    "pytorch",
    "opencv",
    "spacy",
    "nltk",
    "beautifulsoup",
    "selenium",
    "sqlalchemy",
    "alembic",
    "celery",
    "redis",
    # AI / ML
    "machine learning",
    "deep learning",
    "nlp",
    "computer vision",
    "generative ai",
    "llm",
    "openai",
    "langchain",
    "langgraph",
    "rag",
    "huggingface",
    "sentence-transformers",
    "embeddings",
    "vector database",
    "pinecone",
    "chromadb",
    "faiss",
    # QA / Testing
    "manual testing",
    "automation testing",
    "quality assurance",
    "selenium",
    "pytest",
    "unittest",
    "postman",
    "jira",
    # Tools
    "linux",
    "ubuntu",
    "postman",
    "swagger",
    "openapi",
    "vscode",
    "pycharm",
    # Methodologies
    "agile",
    "scrum",
    "kanban",
    # CMS / Ecommerce
    "wordpress",
    "woocommerce",
    "shopify",
    "magento",
    # Miscellaneous
    "microservices",
    "oauth2",
    "jwt",
    "rabbitmq",
    "websocket",
    "elasticsearch",
    # Business Analyst (BA)
    "business analyst",
    "business analysis",
    "requirement gathering",
    "requirements elicitation",
    "requirement analysis",
    "functional requirements",
    "non-functional requirements",
    "brd",
    "frd",
    "srs",
    "user stories",
    "use cases",
    "acceptance criteria",
    "gap analysis",
    "process mapping",
    "workflow analysis",
    "business process modeling",
    "bpmn",
    "uml",
    "wireframing",
    "prototyping",
    "mockups",
    "figma",
    "balsamiq",
    "visio",
    "jira",
    "confluence",
    "agile",
    "scrum",
    "kanban",
    "stakeholder management",
    "stakeholder communication",
    "client communication",
    "documentation",
    "sql",
    "excel",
    "advanced excel",
    "power bi",
    "tableau",
    "data analysis",
    "reporting",
    "dashboard",
    "market research",
    "risk analysis",
    "change management",
    "acceptance testing",
    "uat",
    "a/b testing",
]
